In [19]:
import pandas as pd
import numpy as np

In [2]:
d = pd.read_csv("sam_wild")

In [3]:
print (d)

      Sensor type          x       y       z   time (ms)
0             emg  3323.0000  0.0000  0.0000      12.029
1             acc    -0.0970 -0.0850  0.9375      15.446
2             emg  3606.0000  0.0000  0.0000      25.727
3             acc    -0.1250 -0.1010  0.9335      27.404
4             emg  3876.0000  0.0000  0.0000      38.260
5             acc    -0.1210 -0.0780  0.9062      39.918
6             emg  4094.0000  0.0000  0.0000      50.061
7             acc    -0.1320 -0.0660  0.8828      51.678
8             emg  4191.0000  0.0000  0.0000      61.699
9             acc    -0.1560 -0.0820  0.9296      63.312
10            emg  4479.0000  0.0000  0.0000      73.369
11            acc    -0.1440 -0.0890  0.9179      74.979
12            emg  4641.0000  0.0000  0.0000      85.210
13            acc    -0.1320 -0.0780  0.8906      86.821
14            emg  4728.0000  0.0000  0.0000      96.829
15            acc    -0.1010 -0.0700  0.8671      98.439
16            emg  4859.0000  0

In [18]:
d_drop = d.drop("Sensor type", axis=1)
print (d_drop)

               x       y       z   time (ms)
0      3323.0000  0.0000  0.0000      12.029
1        -0.0970 -0.0850  0.9375      15.446
2      3606.0000  0.0000  0.0000      25.727
3        -0.1250 -0.1010  0.9335      27.404
4      3876.0000  0.0000  0.0000      38.260
5        -0.1210 -0.0780  0.9062      39.918
6      4094.0000  0.0000  0.0000      50.061
7        -0.1320 -0.0660  0.8828      51.678
8      4191.0000  0.0000  0.0000      61.699
9        -0.1560 -0.0820  0.9296      63.312
10     4479.0000  0.0000  0.0000      73.369
11       -0.1440 -0.0890  0.9179      74.979
12     4641.0000  0.0000  0.0000      85.210
13       -0.1320 -0.0780  0.8906      86.821
14     4728.0000  0.0000  0.0000      96.829
15       -0.1010 -0.0700  0.8671      98.439
16     4859.0000  0.0000  0.0000     108.450
17       -0.1170 -0.0700  0.8945     110.060
18     4962.0000  0.0000  0.0000     120.260
19       -0.1210 -0.1010  0.8984     121.870
20     5052.0000  0.0000  0.0000     131.920
21       -

In [16]:
d_matrix = d_drop.as_matrix()

In [17]:
print (d_matrix)

[[  3.32300000e+03   0.00000000e+00   0.00000000e+00   1.20290000e+01]
 [ -9.70000000e-02  -8.50000000e-02   9.37500000e-01   1.54460000e+01]
 [  3.60600000e+03   0.00000000e+00   0.00000000e+00   2.57270000e+01]
 ..., 
 [  1.02730000e+00   1.87500000e-01  -5.74000000e-01   2.36609000e+05]
 [  7.59500000e+03   0.00000000e+00   0.00000000e+00   2.36619000e+05]
 [  1.00300000e+00              nan              nan              nan]]


In [20]:
n_array = np.array(d_matrix)

In [21]:
print (n_array)

[[  3.32300000e+03   0.00000000e+00   0.00000000e+00   1.20290000e+01]
 [ -9.70000000e-02  -8.50000000e-02   9.37500000e-01   1.54460000e+01]
 [  3.60600000e+03   0.00000000e+00   0.00000000e+00   2.57270000e+01]
 ..., 
 [  1.02730000e+00   1.87500000e-01  -5.74000000e-01   2.36609000e+05]
 [  7.59500000e+03   0.00000000e+00   0.00000000e+00   2.36619000e+05]
 [  1.00300000e+00              nan              nan              nan]]


In [25]:
n_conc = np.concatenate((n_array[::2], n_array[1::2]), axis = 1)
print (n_conc)

[[  3.32300000e+03   0.00000000e+00   0.00000000e+00 ...,  -8.50000000e-02
    9.37500000e-01   1.54460000e+01]
 [  3.60600000e+03   0.00000000e+00   0.00000000e+00 ...,  -1.01000000e-01
    9.33500000e-01   2.74040000e+01]
 [  3.87600000e+03   0.00000000e+00   0.00000000e+00 ...,  -7.80000000e-02
    9.06200000e-01   3.99180000e+01]
 ..., 
 [  7.65500000e+03   0.00000000e+00   0.00000000e+00 ...,   1.79600000e-01
   -5.15000000e-01   2.36599000e+05]
 [  7.63100000e+03   0.00000000e+00   0.00000000e+00 ...,   1.87500000e-01
   -5.74000000e-01   2.36609000e+05]
 [  7.59500000e+03   0.00000000e+00   0.00000000e+00 ...,              nan
               nan              nan]]


In [29]:
for p in n_conc: print (p)

[  3.32300000e+03   0.00000000e+00   0.00000000e+00   1.20290000e+01
  -9.70000000e-02  -8.50000000e-02   9.37500000e-01   1.54460000e+01]
[  3.60600000e+03   0.00000000e+00   0.00000000e+00   2.57270000e+01
  -1.25000000e-01  -1.01000000e-01   9.33500000e-01   2.74040000e+01]
[  3.87600000e+03   0.00000000e+00   0.00000000e+00   3.82600000e+01
  -1.21000000e-01  -7.80000000e-02   9.06200000e-01   3.99180000e+01]
[  4.09400000e+03   0.00000000e+00   0.00000000e+00   5.00610000e+01
  -1.32000000e-01  -6.60000000e-02   8.82800000e-01   5.16780000e+01]
[  4.19100000e+03   0.00000000e+00   0.00000000e+00   6.16990000e+01
  -1.56000000e-01  -8.20000000e-02   9.29600000e-01   6.33120000e+01]
[  4.47900000e+03   0.00000000e+00   0.00000000e+00   7.33690000e+01
  -1.44000000e-01  -8.90000000e-02   9.17900000e-01   7.49790000e+01]
[  4.64100000e+03   0.00000000e+00   0.00000000e+00   8.52100000e+01
  -1.32000000e-01  -7.80000000e-02   8.90600000e-01   8.68210000e+01]
[  4.72800000e+03   0.00000

In [30]:
n_conc = n_conc[:-1]
print (n_conc)

[[  3.32300000e+03   0.00000000e+00   0.00000000e+00 ...,  -8.50000000e-02
    9.37500000e-01   1.54460000e+01]
 [  3.60600000e+03   0.00000000e+00   0.00000000e+00 ...,  -1.01000000e-01
    9.33500000e-01   2.74040000e+01]
 [  3.87600000e+03   0.00000000e+00   0.00000000e+00 ...,  -7.80000000e-02
    9.06200000e-01   3.99180000e+01]
 ..., 
 [  7.75800000e+03   0.00000000e+00   0.00000000e+00 ...,   2.14800000e-01
   -4.57000000e-01   2.36588000e+05]
 [  7.65500000e+03   0.00000000e+00   0.00000000e+00 ...,   1.79600000e-01
   -5.15000000e-01   2.36599000e+05]
 [  7.63100000e+03   0.00000000e+00   0.00000000e+00 ...,   1.87500000e-01
   -5.74000000e-01   2.36609000e+05]]


In [31]:
n_del = np.delete(n_conc, [1, 2], axis = 1)
print (n_del)

[[  3.32300000e+03   1.20290000e+01  -9.70000000e-02  -8.50000000e-02
    9.37500000e-01   1.54460000e+01]
 [  3.60600000e+03   2.57270000e+01  -1.25000000e-01  -1.01000000e-01
    9.33500000e-01   2.74040000e+01]
 [  3.87600000e+03   3.82600000e+01  -1.21000000e-01  -7.80000000e-02
    9.06200000e-01   3.99180000e+01]
 ..., 
 [  7.75800000e+03   2.36587000e+05   9.76500000e-01   2.14800000e-01
   -4.57000000e-01   2.36588000e+05]
 [  7.65500000e+03   2.36598000e+05   1.00000000e+00   1.79600000e-01
   -5.15000000e-01   2.36599000e+05]
 [  7.63100000e+03   2.36608000e+05   1.02730000e+00   1.87500000e-01
   -5.74000000e-01   2.36609000e+05]]
